In [ ]:
# Importing the necessary packages
import pandas as pd
import numpy as np
import keras
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold

import warnings
warnings.filterwarnings('ignore')

In [ ]:
# load pima indians dataset
dataset = np.loadtxt("/content/pima-indians-diabetes.csv", delimiter=",")

In [ ]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [ ]:
# load pima indians dataset
#dataset = pd.read_csv("pima-indians-diabetes.csv", delimiter=",")

In [ ]:
X = dataset[:,0:8]
y = dataset[:,8]

In [ ]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [ ]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [ ]:
# Standardization
a = StandardScaler()
a.fit(X)
X_standardized = a.transform(X)

In [ ]:
X_standardized

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
pd.DataFrame(X_standardized).describe()

0             1             2             3             4  \
count  7.680000e+02  7.680000e+02  7.680000e+02  7.680000e+02  7.680000e+02   
mean  -8.789266e-17 -9.251859e-18  1.503427e-17  8.211024e-17 -4.972874e-17   
std    1.000652e+00  1.000652e+00  1.000652e+00  1.000652e+00  1.000652e+00   
min   -1.141852e+00 -3.783654e+00 -3.572597e+00 -1.288212e+00 -6.928906e-01   
25%   -8.448851e-01 -6.852363e-01 -3.673367e-01 -1.288212e+00 -6.928906e-01   
50%   -2.509521e-01 -1.218877e-01  1.496408e-01  1.545332e-01 -4.280622e-01   
75%    6.399473e-01  6.057709e-01  5.632228e-01  7.190857e-01  4.120079e-01   
max    3.906578e+00  2.444478e+00  2.734528e+00  4.921866e+00  6.652839e+00   

                  5             6             7  
count  7.680000e+02  7.680000e+02  7.680000e+02  
mean   2.960595e-15  1.905883e-15  2.081668e-16  
std    1.000652e+00  1.000652e+00  1.000652e+00  
min   -4.060474e+00 -1.189553e+00 -1.041549e+00  
25%   -5.955785e-01 -6.889685e-01 -7.862862e-01  
50%    9.419788e-04 -3.001282e-01 -3.608474e-01  
75%    5.847705e-01  4.662269e-01  6.602056e-01  
max    4.455807e+00  5.883565e+00  4.063716e+00

#### ****Tuning of Hyperparameters :- ****

1.   Batch Size
2.   Epochs



In [ ]:
!pip install scikeras

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.optimizers import Adam

# Sequential        --> from keras.models
# keras             --> easier to build and train neural network
# Dense layers      --> core building blocks of MLPs (Connect 2nodes through line)
# KerasClassifier   --> tasks like cross-validation, hyperparameter tuning
# GridSearchCV      --> Reduce error (hyperparameter optimization --> best combination of model parameters to improve performance)
# Use adam optimizer--> Varient of minibatch (momntum , nestro momentum ,Adam , rms prob, adadelta)


In [ ]:
# create model
def create_model():
    model = Sequential(name='Hypterparameter-Tuning-Dummy')
    model.add(Dense(12, input_dim=8, kernel_initializer='uniform', activation='relu'))
    model.add(Dense(8,kernel_initializer='uniform', activation='relu'))
    model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

    adam=Adam(learning_rate=0.01)
    model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

# 12 nodes input  layer
# 8  nodes hidden later  (X columns)
# 1 output
# kernel_initializer  --> these are initial weights ( u can take uniform ,norm , 0)
# It sets the learning rate for the optimizer to 0.01
# model.compile       --> Put every thing together
# loss                --> (where the output is either 0 or 1), sigmoid activation in the output layer produce)
# adam                --> (weights and biases) are updated during training to reduce the loss.

In [ ]:
# Create the model
model = KerasClassifier(build_fn = create_model,verbose = 1)


# Define the grid search parameters
batch_size = [20,25,30]
epochs = [10,20,40]


# Make a dictionary of the grid search parameters
param_grid = dict(batch_size = batch_size,epochs = epochs)


# Build and fit the GridSearchCV
grid = GridSearchCV(estimator = model,param_grid = param_grid,cv = KFold(n_splits=3),verbose = 10)
grid_result = grid.fit(X_standardized,y)


# create_model  --> function ni call chesthunam
# verbose = 1   --> is used to display output
# batch_size    -->
# epoches       -->
# bat,epoc      --> dictionary chesthunam
# GridSearchCV  --> Reduce error (hyperparameter optimization --> best combination of model parameters to improve performance
# Gridsearchcv  --> Use kfold cross validation


Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV 1/3; 1/9] START batch_size=20, epochs=10....................................
Epoch 1/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6910 - loss: 0.6673
Epoch 2/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.4945 
Epoch 3/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8019 - loss: 0.4573  
Epoch 4/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7954 - loss: 0.4275 
Epoch 5/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7962 - loss: 0.4282
Epoch 6/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7890 - loss: 0.4336
Epoch 7/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7842 - loss: 0.4662 
Epoch 8/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8017 - loss: 0.4474
Epoch 9/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8060 - loss: 0.4434
Epoch 10/10
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8012 - loss: 0.4162
13/13 ━━━━━━━

In [ ]:
# Summarize the results
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

# 1st line is enoufgh to find the best results -->(print('Best :)
# grid_result = grid.fit(X_standardized,y)--> best_score_ , best_params_

# for loop is used to print all the results (mean, stdev, param) batch_size =20 , epoches= 10 ,20 , 40

# Best --> batch_size': 20, 'epochs': 10

Best : 0.77734375, using {'batch_size': 20, 'epochs': 10}
0.77734375,0.025315393353155705 with: {'batch_size': 20, 'epochs': 10}
0.7552083333333334,0.032578114591658346 with: {'batch_size': 20, 'epochs': 20}
0.7682291666666666,0.019225030026345572 with: {'batch_size': 20, 'epochs': 40}
0.7734375,0.03314563036811941 with: {'batch_size': 25, 'epochs': 10}
0.765625,0.036225072248030094 with: {'batch_size': 25, 'epochs': 20}
0.75390625,0.03141233875472609 with: {'batch_size': 25, 'epochs': 40}
0.7278645833333334,0.03737682316251907 with: {'batch_size': 30, 'epochs': 10}
0.7434895833333334,0.01573313277811793 with: {'batch_size': 30, 'epochs': 20}
0.7721354166666666,0.031304206458779446 with: {'batch_size': 30, 'epochs': 40}


#### Tuning of Hyperparameters:- Learning rate and Drop out rate

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.optimizers import Adam

# Defining the model

def create_model(dropout_rate):
    model = Sequential()
    model.add(Dense(8,input_dim = 8,kernel_initializer = 'normal',activation = 'relu'))
    model.add(Dropout(dropout_rate))    # input layer
    model.add(Dense(12,input_dim = 8,kernel_initializer = 'normal',activation = 'relu'))
    model.add(Dropout(dropout_rate))    # hidden layer
    model.add(Dense(1,activation = 'sigmoid'))
    return model

# Create the model

model = KerasClassifier(model=create_model, loss="binary_crossentropy", optimizer="Adam", epochs=10, batch_size=20, verbose=0)

# Define the grid search parameters

learning_rate = [0.001,0.01,0.1]
dropout_rate = [0.0,0.1,0.2]        # 0% , 10% , 20%




# Ensure neither over or underfit .During each training iteration, dropout randomly sets a fraction of the neurons in a layer to zero. This means that these neurons do not contribute to the forward or backward pass of the network for that particular iteration.

# Make a dictionary of the grid search parameters

param_grids = dict(optimizer__learning_rate = learning_rate,model__dropout_rate = dropout_rate)

# Build and fit the GridSearchCV

grid = GridSearchCV(estimator = model, param_grid = param_grids, cv = KFold(n_splits=3), verbose = 10)
grid_result = grid.fit(X_standardized,y)


Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV 1/3; 1/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.001.....
[CV 1/3; 1/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.001;, score=0.750 total time=   1.8s
[CV 2/3; 1/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.001.....
[CV 2/3; 1/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.001;, score=0.711 total time=   1.7s
[CV 3/3; 1/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.001.....
[CV 3/3; 1/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.001;, score=0.801 total time=   1.8s
[CV 1/3; 2/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.01......
[CV 1/3; 2/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.01;, score=0.758 total time=   1.8s
[CV 2/3; 2/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.01......
[CV 2/3; 2/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.01;, score=0.738 total time=   2.5s
[C

In [ ]:
# Summarize the results
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))

means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

# best --> 'optimizer__learning_rate': 0.001

Best : 0.7682291666666666, using {'model__dropout_rate': 0.0, 'optimizer__learning_rate': 0.001}
0.7682291666666666,0.03669011146772232 with: {'model__dropout_rate': 0.0, 'optimizer__learning_rate': 0.001}
0.7682291666666666,0.025779934730759544 with: {'model__dropout_rate': 0.0, 'optimizer__learning_rate': 0.01}
0.7434895833333334,0.032578114591658346 with: {'model__dropout_rate': 0.0, 'optimizer__learning_rate': 0.1}
0.7591145833333334,0.03556380282225954 with: {'model__dropout_rate': 0.1, 'optimizer__learning_rate': 0.001}
0.7604166666666666,0.024359748611809513 with: {'model__dropout_rate': 0.1, 'optimizer__learning_rate': 0.01}
0.7395833333333334,0.009743899444723805 with: {'model__dropout_rate': 0.1, 'optimizer__learning_rate': 0.1}
0.7591145833333334,0.03498705427745938 with: {'model__dropout_rate': 0.2, 'optimizer__learning_rate': 0.001}
0.7630208333333334,0.024773824987552668 with: {'model__dropout_rate': 0.2, 'optimizer__learning_rate': 0.01}
0.734375,0.020914555213813815 wit

#### Tuning of Hyperparameters:- Activation Function and Kernel Initializer

In [ ]:
# Defining the model

def create_model(activation_function,init):
    model = Sequential()
    model.add(Dense(8,input_dim = 8,kernel_initializer = init,activation = activation_function))
    model.add(Dropout(0))
    model.add(Dense(12,input_dim = 8,kernel_initializer = init,activation = activation_function))
    model.add(Dropout(0))
    model.add(Dense(1,activation = 'sigmoid'))


    return model

# Create the model
adam= Adam(learning_rate=0.001)
model = KerasClassifier(model=create_model, loss="binary_crossentropy", optimizer=adam, epochs=20, batch_size=25, verbose=0)
# Define the grid search parameters
activation_function = ['softmax','relu','tanh','linear']
init = ['uniform','normal','zero']

# Make a dictionary of the grid search parameters
param_grids = dict(model__activation_function = activation_function,model__init = init)

# Build and fit the GridSearchCV

grid = GridSearchCV(estimator = model,param_grid = param_grids,cv = KFold(),verbose = 10)
grid_result = grid.fit(X_standardized,y)



Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 1/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.649 total time=   4.7s
[CV 2/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 2/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.584 total time=   2.4s
[CV 3/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 3/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.630 total time=   2.3s
[CV 4/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 4/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.745 total time=   2.4s
[CV 5/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 5/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.647 total time=  

In [ ]:
# Summarize the results
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

# best values : activation_function': 'tanh', 'model__init': 'uniform

Best : 0.7722094898565487, using {'model__activation_function': 'tanh', 'model__init': 'uniform'}
0.7514048043459809,0.044452905944659 with: {'model__activation_function': 'softmax', 'model__init': 'uniform'}
0.7501061030472794,0.04132992927889901 with: {'model__activation_function': 'softmax', 'model__init': 'normal'}
0.7527119938884644,0.04731724730583499 with: {'model__activation_function': 'softmax', 'model__init': 'zero'}
0.7656820303879128,0.040505709001637774 with: {'model__activation_function': 'relu', 'model__init': 'uniform'}
0.7631100925218572,0.03644801472201612 with: {'model__activation_function': 'relu', 'model__init': 'normal'}
0.6511586452762923,0.05244525561493349 with: {'model__activation_function': 'relu', 'model__init': 'zero'}
0.7722094898565487,0.036220455170209324 with: {'model__activation_function': 'tanh', 'model__init': 'uniform'}
0.7709192768016297,0.04555211577244252 with: {'model__activation_function': 'tanh', 'model__init': 'normal'}
0.6511586452762923,0.0

#### Tuning of Hyperparameter :-Number of Neurons in activation layer

In [ ]:
# Defining the model

def create_model(neuron1=8, neuron2=12): # Set default values for neuron1-x and neuron2-y
    model = Sequential()
    model.add(Dense(neuron1, input_dim=8, kernel_initializer='uniform', activation='linear'))
    model.add(Dropout(0.1))
    model.add(Dense(neuron2, kernel_initializer='uniform', activation='linear'))
    model.add(Dropout(0.1))
    model.add(Dense(1, activation='sigmoid'))

    # Updated Line to fix the error
    adam = Adam(learning_rate=0.001)  # Change 'lr' to 'learning_rate'
    model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

# Create the model
model = KerasClassifier(build_fn=create_model, verbose=0, batch_size=40, epochs=50)

# Define the grid search parameters
neuron1 = [4, 8, 16]
neuron2 = [2, 4, 8]

# Make a dictionary of the grid search parameters
# Updated to correctly pass parameters to the KerasClassifier
param_grids = dict(model__neuron1=neuron1, model__neuron2=neuron2)

# Build and fit the GridSearchCV
grid = GridSearchCV(estimator=model, param_grid=param_grids, cv=KFold(), verbose=10)
grid_result = grid.fit(X_standardized, y)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV 1/5; 1/9] START model__neuron1=4, model__neuron2=2..........................
[CV 1/5; 1/9] END model__neuron1=4, model__neuron2=2;, score=0.766 total time=   4.3s
[CV 2/5; 1/9] START model__neuron1=4, model__neuron2=2..........................
[CV 2/5; 1/9] END model__neuron1=4, model__neuron2=2;, score=0.721 total time=   5.7s
[CV 3/5; 1/9] START model__neuron1=4, model__neuron2=2..........................
[CV 3/5; 1/9] END model__neuron1=4, model__neuron2=2;, score=0.760 total time=   4.3s
[CV 4/5; 1/9] START model__neuron1=4, model__neuron2=2..........................
[CV 4/5; 1/9] END model__neuron1=4, model__neuron2=2;, score=0.837 total time=   4.2s
[CV 5/5; 1/9] START model__neuron1=4, model__neuron2=2..........................
[CV 5/5; 1/9] END model__neuron1=4, model__neuron2=2;, score=0.758 total time=   5.3s
[CV 1/5; 2/9] START model__neuron1=4, model__neuron2=4..........................
[CV 1/5; 2/9] END model_

In [ ]:
# Summarize the results
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))

means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

# Best values --> model__neuron1': 4, 'model__neuron2

Best : 0.7709107885578474, using {'model__neuron1': 4, 'model__neuron2': 8}
0.7683048977166624,0.037692040541977494 with: {'model__neuron1': 4, 'model__neuron2': 2}
0.7682879212290977,0.0373617607269985 with: {'model__neuron1': 4, 'model__neuron2': 4}
0.7709107885578474,0.03379385513777502 with: {'model__neuron1': 4, 'model__neuron2': 8}
0.7643833290892115,0.03795436935488736 with: {'model__neuron1': 8, 'model__neuron2': 2}
0.7656990068754774,0.03975947752639414 with: {'model__neuron1': 8, 'model__neuron2': 4}
0.7695951107715814,0.0366348058559436 with: {'model__neuron1': 8, 'model__neuron2': 8}
0.7682879212290976,0.03570660839983507 with: {'model__neuron1': 16, 'model__neuron2': 2}
0.769586622527799,0.035726361641676085 with: {'model__neuron1': 16, 'model__neuron2': 4}
0.7644003055767762,0.03143074607321314 with: {'model__neuron1': 16, 'model__neuron2': 8}


#### Training model with optimum values of Hyperparameters

In [ ]:
from sklearn.metrics import classification_report, accuracy_score

# Defining the model

def create_model():
    model = Sequential()
    model.add(Dense(8,input_dim = 8,kernel_initializer = 'uniform',activation = 'tanh'))
    model.add(Dropout(0.2))
    model.add(Dense(2,kernel_initializer = 'uniform',activation = 'tanh'))
    model.add(Dropout(0.2))
    model.add(Dense(1,activation = 'sigmoid'))

    adam = Adam(learning_rate = 0.001)
    model.compile(loss = 'binary_crossentropy',optimizer = adam,metrics = ['accuracy'])
    return model

# Create the model

model = KerasClassifier(build_fn = create_model,verbose = 0,batch_size = 20,epochs = 10)

# Fitting the model

model.fit(X_standardized,y)

# Predicting using trained model

y_predict = model.predict(X_standardized)

# Printing the metrics
print(accuracy_score(y,y_predict))

0.77734375


# Hyperparameters all at once


The hyperparameter optimization was carried out by taking 2 hyperparameters at once. We may have missed the best values. The performance can be further improved by finding the optimum values of hyperparameters all at once given by the code snippet below.
#### This process is computationally expensive.

In [ ]:
# Not useful
# model.get_params().keys()
# grid.get_params().keys()

dict_keys(['cv', 'error_score', 'estimator__model', 'estimator__build_fn', 'estimator__warm_start', 'estimator__random_state', 'estimator__optimizer', 'estimator__loss', 'estimator__metrics', 'estimator__batch_size', 'estimator__validation_batch_size', 'estimator__verbose', 'estimator__callbacks', 'estimator__validation_split', 'estimator__shuffle', 'estimator__run_eagerly', 'estimator__epochs', 'estimator__class_weight', 'estimator', 'n_jobs', 'param_grid', 'pre_dispatch', 'refit', 'return_train_score', 'scoring', 'verbose'])

In [ ]:
def create_model(learning_rate,dropout_rate,activation_function,init,neuron1=8,neuron2=12):
    model = Sequential()
    model.add(Dense(8,input_dim = 8,kernel_initializer = init,activation = activation_function))
    model.add(Dropout(dropout_rate))
    model.add(Dense(2,input_dim = neuron1,kernel_initializer = init,activation = activation_function))
    model.add(Dropout(dropout_rate))
    model.add(Dense(1,activation = 'sigmoid'))

    adam = Adam(learning_rate = learning_rate)
    model.compile(loss = 'binary_crossentropy',optimizer = adam,metrics = ['accuracy'])
    return model

# Create the model

model = KerasClassifier(model = create_model,verbose = 0,batch_size=batch_size,epochs=epochs)

# Define the grid search parameters

batch_size = [10,20,40]
epochs = [10,50,100]
learning_rate = [0.01,0.001,0.0001]
dropout_rate = [0.2,0.3,0.1]
activation_function = ['softmax','relu','tanh','linear'] # 'relu'
init = ['uniform','normal','zero']  # 'normal


# Make a dictionary of the grid search parameters

param_grids = dict(batch_size = batch_size,epochs = epochs,learning_rate = learning_rate,dropout_rate = dropout_rate,
                   activation_function = activation_function,init = init,neuron1=neuron1 ,neuron2=neuron2)

# Build and fit the GridSearchCV

grid = GridSearchCV(estimator=model, param_grid=param_grids,cv=KFold(), verbose=10)
grid_result = grid.fit(X_standardized, y)



Fitting 5 folds for each of 8748 candidates, totalling 43740 fits
[CV 1/5; 1/8748] START activation_function=softmax, batch_size=10, dropout_rate=0.2, epochs=10, init=uniform, learning_rate=0.01, neuron1=4, neuron2=2


ValueError: Invalid parameter activation_function for estimator KerasClassifier.
This issue can likely be resolved by setting this parameter in the KerasClassifier constructor:
`KerasClassifier(activation_function=softmax)`
Check the list of available parameters with `estimator.get_params().keys()`

In [ ]:
# Summarize the results
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

In [ ]:
!pip install scikeras